name:                nmkp
version:             0.1.0.0
github:              "maartenJacobs/nmkp"
license:             BSD3
author:              "Maarten Jacobs"
maintainer:          "maarten.j.jacobs@gmail.com"
copyright:           "2018 Maarten Jacobs"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/maartenJacobs/nmkp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - gloss
  - gloss-game
  - random
  - linear

executables:
  nmkp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    dependencies:
    - nmkp
